### ISSUE TITLE
Missing update on :Gwrite

### ISSUE THREAD

**Issue by somini** [airblade/vim-gitgutter#278]
If you use [vim-fugitive], it provides useful commands such as `Gwrite` that stage the file and save the buffer. The only problem is that the gutter is not updated.

As of now, my "workaround" is saving the buffer afterwards, so that the autocmds kick in and update the buffer. I think that plugin is doing some kind of wizardry to save buffers without triggering autocmds.

Might be related to https://github.com/tpope/vim-fugitive/issues/348

[vim-fugitive]: https://github.com/tpope/vim-fugitive/blob/master/plugin/fugitive.vim#L1436

**Comment by airblade** [comment]
Is this with files which are already known to git?

**Comment by somini** [comment]
Yes, editing existing files, no edge cases here. :)

**Comment by airblade** [comment]
Here's what I've found so far:

1. vim-gitgutter picks up the `BufWritePost` autocommand fired by vim-fugitive.
2. After the autocommand is noticed, but before vim-gitgutter starts to do its thing, `git-diff` still shows the pre-`Gwrite` diff.
3. After vim-gitgutter has run, `git-diff` reports no changes.

(1) and (3) are expected.  (2) is surprising.  I found (2) by inserting a `sleep 10` above [this line](https://github.com/airblade/vim-gitgutter/blob/b18e23cdfa082dee7da8a2466db5a66907491e5b/plugin/gitgutter.vim#L174) in vim-gitgutter's autocommand, then running the following command in a different terminal once the sleep started:

```sh
git diff --no-ext-diff --no-color -U0  -- Gemfile
```

When run during the sleep, the diff was the same as it was before doing `:Gwrite`.  When run after vim-gitgutter had finished, the diff was empty.

Regarding (2), vim-fugitive [updates git's index](https://github.com/tpope/vim-fugitive/blob/f096152a48bc2506bd460c9f990e50a159a7bbc5/plugin/fugitive.vim#L2142-2171) via `git-update-index`.  I would expect `git-diff` to be 'up to date' once `git-update-index` has returned but I don't know anything about the latter command...

**Comment by airblade** [comment]
Cross-ref tpope/vim-fugitive#503.

**Comment by airblade** [comment]
@tpope If you have a moment, please could you run you eye over this issue and see if anything comes to mind?  I don't understand why git's index isn't up to date by when Fugitive fires the `BufWritePost` autocommand.  Thanks!

**Comment by tpope** [comment]
I see a few things that could be triggering `BufWritePost`. Are you sure you're looking at the correct one?

**Comment by airblade** [comment]
As far as I can tell only one `BufWritePost` is triggered: if I do `:au BufWritePost * echo expand("<abuf>")`, make some edits and execute `:Gwrite`, I just see one message and it shows the expected buffer.

**Comment by airblade** [comment]
Is this the flow for `:Gwrite`?

- [`Gwrite`](https://github.com/tpope/vim-fugitive/blob/f8aa87a4b5551052a41e25af80609e4624dcd58a/plugin/fugitive.vim#L1438) executes `s:Write( ... )`.
- [`s:Write( ... )`](https://github.com/tpope/vim-fugitive/blob/f8aa87a4b5551052a41e25af80609e4624dcd58a/plugin/fugitive.vim#L1442) writes the buffer at some point...maybe? I don't understand what's going on in this function.
- writing the buffer automatically triggers [`BufWriteCmd`](https://github.com/tpope/vim-fugitive/blob/f8aa87a4b5551052a41e25af80609e4624dcd58a/plugin/fugitive.vim#L2694) which executes `s:BufWriteIndexFile()`.
- `s:BufWriteIndexFile()` [updates git's index](https://github.com/tpope/vim-fugitive/blob/f8aa87a4b5551052a41e25af80609e4624dcd58a/plugin/fugitive.vim#L2581-L2585).

If that's broadly what happens, the buffer is written before git's index is updated.  When the `BufWritePost` autocommand is triggered, does Vim execute `BufWritePost` handlers there and then or does it put them to one side for execution after the current script is finished?  If it executes them immediately, this would explain why the index isn't up to date when `BufWritePost` is applied.

**Comment by tpope** [comment]
`s:Write()` writes the buffer twice: once to the current buffer's path, and a second time to the corresponding `fugitive://` path for the index, which triggers `s:BufWriteIndexFile()`. So I would expect at least 2 `BufWritePost` events. Your initial investigation suggests the latter isn't firing.

**Comment by airblade** [comment]
I stepped through this in a debugger and saw fugitive write to the current buffer's real path at line [1522](https://github.com/tpope/vim-fugitive/blob/f8aa87a4b5551052a41e25af80609e4624dcd58a/plugin/fugitive.vim#L1522).  This activated vim-gitgutter's `BufWritePost` handler.

I couldn't make out where or even if `s:BufWriteIndexFile()` was called.

**Comment by airblade** [comment]
@tpope I think I found the problem: `s:Write()` doesn't write to the corresponding `fugitive://` path and so `s:BufWriteIndexFile()` isn't triggered. (At least when a plain `:Gwrite` is executed.)

Instead `s:Write()` writes the buffer [here](https://github.com/tpope/vim-fugitive/blob/1ecd12d523ffe031b5840316eeae1f24dd8920e4/plugin/fugitive.vim#L1522) and adds the file to the index [here](https://github.com/tpope/vim-fugitive/blob/1ecd12d523ffe031b5840316eeae1f24dd8920e4/plugin/fugitive.vim#L1528) via `git-add`.  The former naturally triggers a `BufWritePost` but the index isn't updated at that point; the latter doesn't trigger a `BufWritePost`.

I solved the problem, at least for this issue, by adding the following line immediately after the `git-add`:

```viml
execute 'doautocmd BufWritePost '.s:fnameescape(expand('%:p'))
```

Taking a step back, that doesn't seem like quite the right autocommand to indicate the index has been updated – but I'm not sure what would be better.  Maybe a custom user autocommand?

Happy to send a pull request if it would help.

**Comment by tpope** [comment]
I think the right autocommand would be `BufWritePost fugitive://.../.git/0/...`.

**Comment by deiwin** [comment]
What's the status of this?

**Comment by airblade** [comment]
@delwin As far as I understand, there's nothing to do from the vim-gitgutter end; once the correct autocommand is added to Fugitive, vim-gitgutter should pick it up automatically.

I'd be happy to open a pull request on Fugitive but I'm not sure how to convert the pattern @tpope kindly suggested into a specific autocommand pattern.

**Comment by tpope** [comment]
Probably something like `exe 'doautocmd BufWritePost' s:fnameescape(zero)`.

**Comment by airblade** [comment]
Fixed by tpope/vim-fugitive@57afba5bdd49b59d57485f90aa0cf3f3a6c47f63.

**Comment by deiwin** [comment]
Works perfectly. Thank you!

**Comment by somini** [comment]
I can confirm this too, thanks.

**Comment by liushapku** [comment]
I use `vim-signify` instead of `gitgutter`. The problem seems to still exist

**Comment by airblade** [comment]
@liushapku Please see #502.
